name: Imagepils tests and package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run lint with flake8 
        run: |
          # stop the build if there are Python syntax errors or undefined names
          # and exit with errors. flake configuration is in the repository
          flake8 . --config .flake8
      - name: Install package
        run: |
          python setup.py develop
      - name: Test with pytest (with coverage)
        run: |
          pytest tests -v --cov=./imagepills --cov-report=xml:./coverage.xml --cov-report term-missing
      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_GH_IMAGEPILS }}
          file: ./coverage.xml
          name: rich
          flags: unittests
          env_vars: OS,PYTHON
